# Generated by Django 5.0.2 on 2024-03-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_user_track_user_tracks_alter_user_sex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[("M", "Мужской"), ("F", "Женский"), ("", "Не указано")],
                max_length=1,
                verbose_name="Пол",
            ),
        ),
    ]
