# Generated by Django 5.0.2 on 2024-04-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_sex"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_active_link",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
    ]
