# Generated by Django 5.0.2 on 2024-04-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_is_active_link_user_is_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="yandex_id",
            field=models.BigIntegerField(
                blank=True, null=True, unique=True, verbose_name="ID в Yandex"
            ),
        ),
    ]
