# Generated by Django 5.0.2 on 2024-04-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_is_active_link_user_is_public"),
        ("web", "0002_remove_track_genres_track_genre_alter_artist_avatar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.URLField(max_length=511, verbose_name="фотография"),
        ),
        migrations.AlterField(
            model_name="user",
            name="birthday",
            field=models.DateField(blank=True, null=True, verbose_name="дата рождения"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="почта"),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=150, verbose_name="имя"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active_link",
            field=models.BooleanField(
                default=True, verbose_name="включена ссылка с запросом на сравнение?"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_private",
            field=models.BooleanField(default=False, verbose_name="виден в поиске?"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=150, verbose_name="фамилия"),
        ),
        migrations.AlterField(
            model_name="user",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[("M", "Мужской"), ("F", "Женский"), ("", "Не указано")],
                max_length=1,
                verbose_name="пол",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="tracks",
            field=models.ManyToManyField(to="web.track", verbose_name="треки"),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=150, unique=True, verbose_name="никнейм"),
        ),
        migrations.AlterField(
            model_name="user",
            name="yandex_id",
            field=models.IntegerField(
                blank=True, null=True, unique=True, verbose_name="идентификатор в Яндексе"
            ),
        ),
    ]
