# Generated by Django 5.0.2 on 2024-04-26 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_user_avatar_alter_user_birthday_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Refresh",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[("VK", "ВКонтакте"), ("Yandex", "Яндекс")],
                        max_length=15,
                        verbose_name="музыкальный сервис",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("auto", "автоматически"), ("manual", "вручную")],
                        max_length=7,
                        verbose_name="способ обновления",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("in_process", "в процессе"), ("finished", "завершено")],
                        default="in_process",
                        max_length=15,
                        verbose_name="статус обновления",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="начато в")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="изменено в")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("value", models.CharField(max_length=255, verbose_name="токен")),
                (
                    "service",
                    models.CharField(
                        choices=[("VK", "ВКонтакте"), ("Yandex", "Яндекс")],
                        max_length=15,
                        verbose_name="музыкальный сервис",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
        ),
    ]
