# Generated by Django 5.0.2 on 2024-04-26 12:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_refresh_token"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="token",
            unique_together={("user", "service")},
        ),
    ]
