# Generated by Django 5.0.4 on 2024-05-03 01:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_user_yandex_id"),
        ("users", "0007_alter_token_unique_together"),
    ]

    operations = []
