# Generated by Django 5.0.4 on 2024-05-03 01:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_merge_20240503_0423"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="yandex_id",
            field=models.BigIntegerField(
                blank=True, null=True, unique=True, verbose_name="идентификатор в Яндексе"
            ),
        ),
    ]
