# Generated by Django 5.0.2 on 2024-05-05 21:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_alter_user_yandex_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["-last_login"]},
        ),
    ]
