# Generated by Django 5.0.2 on 2024-03-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("yandex_id", models.IntegerField(unique=True, verbose_name="ID в Yandex")),
                ("name", models.CharField(max_length=255, verbose_name="Имя")),
                ("avatar", models.CharField(max_length=511, verbose_name="URL фотографии профиля")),
            ],
            options={
                "verbose_name": "артист",
                "verbose_name_plural": "артисты",
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=63, unique=True, verbose_name="Жанр")),
            ],
            options={
                "verbose_name": "жанр",
                "verbose_name_plural": "жанры",
            },
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("yandex_id", models.IntegerField(unique=True, verbose_name="ID в Yandex")),
                ("title", models.CharField(verbose_name="Название")),
                ("release_date", models.DateTimeField(max_length=255, verbose_name="Дата выхода")),
                ("cover", models.URLField(max_length=511, verbose_name="URL обложки")),
                ("artist", models.ManyToManyField(to="web.artist", verbose_name="Артист")),
                ("genre", models.ManyToManyField(to="web.genre", verbose_name="Жанр")),
            ],
            options={
                "verbose_name": "песня",
                "verbose_name_plural": "песни",
            },
        ),
    ]
