# Generated by Django 5.0.2 on 2024-04-19 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="track",
            name="genres",
        ),
        migrations.AddField(
            model_name="track",
            name="genre",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="web.genre",
                verbose_name="жанр",
            ),
        ),
        migrations.AlterField(
            model_name="artist",
            name="avatar",
            field=models.URLField(max_length=511, verbose_name="фотография"),
        ),
        migrations.AlterField(
            model_name="artist",
            name="name",
            field=models.CharField(max_length=255, verbose_name="имя"),
        ),
        migrations.AlterField(
            model_name="artist",
            name="yandex_id",
            field=models.IntegerField(unique=True, verbose_name="идентификатор в Яндексе"),
        ),
        migrations.AlterField(
            model_name="genre",
            name="title",
            field=models.CharField(max_length=63, unique=True, verbose_name="название"),
        ),
        migrations.AlterField(
            model_name="track",
            name="artists",
            field=models.ManyToManyField(to="web.artist", verbose_name="артисты"),
        ),
        migrations.AlterField(
            model_name="track",
            name="cover",
            field=models.URLField(max_length=511, verbose_name="обложка"),
        ),
        migrations.AlterField(
            model_name="track",
            name="release_date",
            field=models.DateTimeField(verbose_name="дата выхода"),
        ),
        migrations.AlterField(
            model_name="track",
            name="title",
            field=models.CharField(max_length=255, verbose_name="название"),
        ),
        migrations.AlterField(
            model_name="track",
            name="yandex_id",
            field=models.IntegerField(unique=True, verbose_name="идентификатор в Яндексе"),
        ),
    ]
