# Generated by Django 5.0.2 on 2024-04-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0002_remove_track_genres_track_genre_alter_artist_avatar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="yandex_id",
            field=models.BigIntegerField(unique=True, verbose_name="идентификатор в Яндексе"),
        ),
        migrations.AlterField(
            model_name="track",
            name="yandex_id",
            field=models.BigIntegerField(unique=True, verbose_name="идентификатор в Яндексе"),
        ),
    ]
