# Generated by Django 5.0.4 on 2024-05-21 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0003_alter_artist_yandex_id_alter_track_yandex_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="genre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="web.genre",
                verbose_name="жанр",
            ),
        ),
        migrations.AlterField(
            model_name="track",
            name="release_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="дата выхода"),
        ),
    ]
